/* Group Members: Mohammed Arab, Khanh Le, Ben Cacic
   Course: COMP 3659
   Assignment: Assignment 02
   Instructor: Marc Schroeder
   File Name: stat_table.h
 */
#ifndef STAT_TABLE_H
#define STAT_TABLE_H

#include "processes.h"
#include "output.h"

/* Funtion name: statistic_table
   Inputs: Process process[] - Array of processes
           int choice - chosen scheduling alogrithms
   Ouputs: None
   Description: 
*/
void statistic_table(Process process[], int choice);

/* Funtion name: print_table_priority
   Inputs: Process process[] - Array of processes
   Ouputs: None
   Description: The function prints the statistic table
   of each process to the screen based on the selected
   scheduling algorithm(s).
*/
static void print_table_priority(Process process[]);

/* Funtion name: print_table_FCFS
   Inputs: Process process[] - Array of processes
   Ouputs: None
   Description: The function prints the statistic table
   of each process that is generated by the First-come-first
   -serve algorithms to the screen
*/
static void print_table_FCFS(Process process[]);

/* Funtion name: print_table_ExpectedBurst
   Inputs: Process process[] - Array of processes
           int choice - chosen scheduling alogrithms
   Ouputs: None
   Description: The function prints the statistic table
   of each process that is generated by the Shortest Job
   First or Shortest Remaing Time algorithms to the screen
*/
static void print_table_ExpectedBurst(Process process[], int choice);

/* Funtion name: print_label
   Inputs: int choice - chosen scheduling alogrithms
   Ouputs: None
   Description: The function prints the statistic lable
   row to the screen based on the selected algorithm(s)
*/
static void print_label(int choice);

/* Funtion name: print_lable_name
   Inputs: None
   Ouputs: None
   Description: The function prints the statistic lable
   name to the screen. This function is called internally
   inside the output.h library functions by the print_lable
   function to have a complete lable row.
*/
static void print_lable_name();

/* Funtion name: print_table_RR
   Inputs: Process process[]
   Ouputs: None
   Description: The function prints the statistic table
   of each process that is generated by the Round Robin
   algorithm to the screen
*/
static void print_table_RR(Process process[]);

/* Funtion name: print_process_stat
   Inputs: Process process[] - Array of processes
           int index - the current index of the process being 
                       printed
   Ouputs: None
   Description: The function prints the stat of a process 
   specified by the index(current) position of the process
   array based on the selected algorithm to the screen.
   This function is called internally within the output.h
   library functions by any printing stat table function 
   for the selected
   algorithm.
*/
static void print_process_stat(Process process[], int index);

#endif