/* Group Members: Mohammed Arab, Khanh Le, Ben Cacic
   Course: COMP 3659
   Assignment: Assignment 02
   Instructor: Marc Schroeder
   File Name: stat_table.c
 */
#include "stat_table.h"

/* Funtion name: statistic_table
   Inputs: Process process[] - Array of processes
           int choice - chosen scheduling alogrithms
   Ouputs: None
   Description: 
*/
void statistic_table(Process process[], int choice)
{
    if (choice == 5)
    {
        print_table_priority(process);
    } else if (choice == 1){
        print_table_FCFS(process);
    } else if (choice == 2)
    {
        print_table_ExpectedBurst(process,2);
    } else if (choice == 3)
    {
        print_table_ExpectedBurst(process,3);
    }
    else if (choice == 4)
    {
        print_table_RR(process);
    }
    return;
}

/* Funtion name: print_label
   Inputs: int choice - chosen scheduling alogrithms
   Ouputs: None
   Description: The function prints the statistic lable
   row to the screen based on the selected algorithm(s)
*/
static void print_label(int choice)
{
    printf(BOLD CYN);
    if (choice == 5)
    {
        printf(BOLD CYN "+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+--------------+\n");
        print_lable_name();
        printf(BOLD YEL"    Priority  ");
         printf(BOLD CYN); printf("|");
        printf(BOLD CYN "\n+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+--------------+\n");
    } else if (choice == 1) {
        printf(BOLD CYN "+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+\n");
        print_lable_name();
        printf(BOLD CYN "\n+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+\n");
    } else if ((choice == 2) || (choice == 3))
    {
        printf(BOLD CYN "+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+-----------------+\n");
        print_lable_name();
        printf(BOLD YEL"  Expected Burst ");
        printf(BOLD CYN); printf("|");
        printf(BOLD CYN "\n+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+-----------------+\n");
    } else if (choice == 4)
    {
        printf(BOLD CYN "+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+--------------+\n");
        print_lable_name();
        printf(BOLD YEL"  # of Bursts ");
        printf(BOLD CYN); printf("|");
        printf(BOLD CYN "\n+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+--------------+\n");
    }

    return;
}

/* Funtion name: print_lable_name
   Inputs: None
   Ouputs: None
   Description: The function prints the statistic lable
   name to the screen. This function is called internally
   inside the output.h library functions by the print_lable
   function to have a complete lable row.
*/
static void print_lable_name()
{
    printf(BOLD CYN); printf("| ");
    printf(BOLD YEL); printf("PID ");
    printf(BOLD CYN); printf("| ");
    printf(BOLD YEL); printf("Arrival Time ");
    printf(BOLD CYN); printf("| ");
    printf(BOLD YEL); printf("Actual Start ");
    printf(BOLD CYN); printf("| ");
    printf(BOLD YEL); printf("  Burst Time    ");
    printf(BOLD CYN); printf("| ");
    printf(BOLD YEL); printf("Completion Time ");
    printf(BOLD CYN); printf("| ");
    printf(BOLD YEL); printf("Turnaround Time ");
    printf(BOLD CYN); printf("| ");
    printf(BOLD YEL); printf("Waiting Time ");
    printf(BOLD CYN"|");

    return;
}

/* Funtion name: print_table_priority
   Inputs: Process process[] - Array of processes
   Ouputs: None
   Description: The function prints the statistic table
   of each process to the screen based on the selected
   scheduling algorithm(s).
*/
static void print_table_priority(Process process[])
{
    print_label(5);

    for (int i = 0; i < ARR_SIZE; i++)
    {
        print_process_stat(process, i);
        printf(BOLD CYN"|   ");  printf(WHT"  %3d      ",process[i].priority);
        printf(BOLD CYN"|\n");
        printf(BOLD CYN);
        printf(BOLD CYN "+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+--------------+\n");
    }
}

/* Funtion name: print_table_FCFS
   Inputs: Process process[] - Array of processes
   Ouputs: None
   Description: The function prints the statistic table
   of each process that is generated by the First-come-first
   -serve algorithms to the screen
*/
static void print_table_FCFS(Process process[])
{
    print_label(1);
    for (int i = 0; i < ARR_SIZE; i++)
    {
        print_process_stat(process, i);
        printf(BOLD CYN"|\n");
        printf(BOLD CYN);
        printf(BOLD CYN "+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+\n");
    }
    return;
}

/* Funtion name: print_table_ExpectedBurst
   Inputs: Process process[] - Array of processes
   Ouputs: None
   Description: The function prints the statistic table
   of each process that is generated by the Shortest Job
   First or Shortest Remaing Time algorithms to the screen
*/
static void print_table_ExpectedBurst(Process process[], int choice)
{
    print_label(2);
    for (int i = 0; i < ARR_SIZE; i++)
    {
        print_process_stat(process, i);
      
        printf(BOLD CYN"|  "); printf(WHT "%10.2f     ", process[i].estimatedBurstTime);
        printf(BOLD CYN"|\n");
        printf(BOLD CYN);
        printf(BOLD CYN "+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+-----------------+\n");
    }
    return;
}

/* Funtion name: print_table_RR
   Inputs: Process process[]
   Ouputs: None
   Description: The function prints the statistic table
   of each process that is generated by the Round Robin
   algorithm to the screen
*/
static void print_table_RR(Process process[])
{
    print_label(4);
    for (int i = 0; i < ARR_SIZE; i++)
    {
        print_process_stat(process, i);
        printf(BOLD CYN"|     "); printf(WHT "%3d      ", process[i].numberOfBursts); 
        printf(BOLD CYN"|\n");
        printf(BOLD CYN);
        printf(BOLD CYN "+-----+--------------+--------------+-----------------+-----------------+-----------------+--------------+--------------+\n");
    }
    return;
}

/* Funtion name: print_process_stat
   Inputs: Process process[] - Array of processes
           int index - the current index of the process being 
                       printed
           int choice - chosen scheduling alogrithms
   Ouputs: None
   Description: The function prints the stat of a process 
   specified by the index(current) position of the process
   array based on the selected algorithm to the screen.
   This function is called internally within the output.h
   library functions by any printing stat table function 
   for the selected
   algorithm.
*/
static void print_process_stat(Process process[], int index)
{
    // int completionTime;
    printf(BOLD CYN"| ");  printf(WHT "P%d  ",process[index].process_id);
    printf(BOLD CYN"|     "); printf(WHT"%3d      ",process[index].arrival_time);
    printf(BOLD CYN"|     "); printf(WHT"%3d      ",process[index].actualStart);
    printf(BOLD CYN"|     "); printf(WHT"%3d         ",process[index].burst_time);
        
    int completionTime = process[index].completed;
        // process[i].completed = 0;
    printf(BOLD CYN"|       "); printf(WHT "%3d       ",completionTime);
    int turnaroundTime = completionTime - process[index].arrival_time;
    printf(BOLD CYN"|        "); printf(WHT"%3d      ", turnaroundTime);
        // turn_around time - burst time = waiting time
    printf(BOLD CYN"|     "); printf(WHT "%3d      ", (turnaroundTime - process[index].burst_time));
    return;
}